export default {
  Binarize: [0.5],
  BoxBlur: [3, 3, 2],
  GaussianBlur: [2],
  StackBlur: [6],
  BrightnessContrastGimp: [0, 0],
  BrightnessContrastPhotoshop: [0, 0],
  Channels: [1],
  ColorTransformFilter: [1, 1, 1, 1, 0, 0, 0, 0],
  Desaturate: [],
  Dither: [8],
  Edge: [],
  Emboss: [],
  Enrich: [],
  Flip: [false],
  Gamma: [1],
  GrayScale: [],
  HSLAdjustment: [0, 0, 0],
  Invert: [],
  Mosaic: [10],
  Oil: [2, 32],
  Posterize: [8],
  Rescale: [2],
  ResizeNearestNeighbor: [400, 300],
  Resize: [400, 300],
  ResizeBuiltin: [400, 300],
  Sepia: [],
  Sharpen: [3],
  Solarize: [],
  Transpose: [],
  Twril: [0.5, 0.5, 100, 360, 0, true],
  Bilateral: [4, 16],
};
