export default {
  Binarize: [0.5],
  // BoxBlur: [3, 3, 2],
  GaussianBlur: [4],
  // StackBlur: [6],
  BrightnessContrastGimp: [20, 5],
  BrightnessContrastPhotoshop: [40, 15],
  Channels: [1],
  ColorTransformFilter: [5, 5, 5, 5, 0, 0, 0, 0],
  Desaturate: [],
  // Dither: [2],
  Edge: [],
  Emboss: [],
  Enrich: [],
  Gamma: [2],
  GrayScale: [],
  HSLAdjustment: [30, 30, 30],
  Invert: [],
  Mosaic: [16],
  Oil: [4, 150],
  Posterize: [2],
  Rescale: [4],
  Sepia: [],
  Sharpen: [10],
  Solarize: [],
};
